#!/usr/bin/env python3
"""
my_robot_pkg Launch File

Generated by RobotStudio on 2025-10-30 22:30:35
"""

from launch import LaunchDescription
from launch_ros.actions import Node


def generate_launch_description():
    """Generate launch description with all nodes"""

    return LaunchDescription([
        # subscriber node
        Node(
            package='my_robot_pkg',
            executable='serial_bridge',
            name='serial_bridge',
            output='screen',
            parameters=[{}],
            remappings=[],
        ),
        # publisher node
        Node(
            package='my_robot_pkg',
            executable='imu_sensor',
            name='imu_sensor',
            output='screen',
            parameters=[{}],
            remappings=[],
        ),
        # publisher node
        Node(
            package='my_robot_pkg',
            executable='ultrasonic_sensor',
            name='ultrasonic_sensor',
            output='screen',
            parameters=[{}],
            remappings=[],
        ),
        # subscriber node
        Node(
            package='my_robot_pkg',
            executable='motor_controller',
            name='motor_controller',
            output='screen',
            parameters=[{}],
            remappings=[],
        ),
    ])