#!/usr/bin/env python3
"""
motor_controller - Generated by RobotStudio

ROS2 subscriber node

Generated on: 2025-10-30 22:30:35
"""

import rclpy
from rclpy.node import Node
from rclpy.qos import QoSProfile, ReliabilityPolicy, DurabilityPolicy, HistoryPolicy
from std_msgs.msg import String


class MotorControllerNode(Node):
    """ROS2 subscriber node"""

    def __init__(self):
        super().__init__('motor_controller')

        self.get_logger().info('motor_controller starting...')

        # Subscribers
        # QoS Profile for /topic
        subscriber_qos = QoSProfile(
            reliability=ReliabilityPolicy.RELIABLE,
            durability=DurabilityPolicy.VOLATILE,
            history=HistoryPolicy.KEEP_LAST,
            depth=10
        )
        self.subscriber = self.create_subscription(
            String,
            '/topic',
            self.subscriber_callback,
            subscriber_qos
        )

        self.get_logger().info('motor_controller initialized successfully')

    def subscriber_callback(self, msg):
        """
        Callback for subscriber on topic '/topic'

        Args:
            msg: String message
        """
        self.get_logger().info(f'Received: {msg}')



def main(args=None):
    """Main entry point"""
    rclpy.init(args=args)

    node = MotorControllerNode()

    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    except Exception as e:
        # Handle external shutdown and other exceptions gracefully
        node.get_logger().warn(f'Node interrupted: {type(e).__name__}')
    finally:
        node.get_logger().info('motor_controller shutting down')
        node.destroy_node()

        # Only shutdown if context is still valid
        try:
            if rclpy.ok():
                rclpy.shutdown()
        except Exception:
            # Context already shutdown - this is fine
            pass


if __name__ == '__main__':
    main()